CREATE TABLE tb_role (
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO tb_role (name) VALUES
    ('ROLE_CUSTOMER'),
    ('ROLE_MEMBER'),
    ('ROLE_ADMINISTRATOR');
